---
- name: homebrewのアップデート
  homebrew:
    update_homebrew=yes

- name: fishのインストール
  homebrew:
    name: fish
    state: latest

# - name: fishを選択可能なshellとして追加
#   lineinfile:
#     dest: /etc/shells
#     line: /usr/local/bin/fish
#   become: yes

# - name: 既存のshellを確認する
#   shell: echo $SHELL
#   register: current_shell
#   changed_when: false

# - name: fishをデフォルトのshellにする
#   shell: chsh -s /usr/local/bin/fish
#   become: yes
#   when: current_shell.stdout != '/usr/local/bin/fish'

- name: functionsディレクトリを作る
  file:
    path: ~/.config/fish/functions
    state: directory

- name: fishermanのインストール
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: fisherman経由でプラグインのインストール
  shell: fish -lc "fisher add {{ item }}"
  args:
    creates: ~/.config/fisher/github.com/{{ item }}
  with_items:
    - oh-my-fish/theme-bobthefish
    - jethrokuan/z
    - tuvistavie/fish-ssh-agent
    - rodrigobdz/fish-apple-touchbar

- name: fisherman経由でgistで定義したカスタムキーバインドをインストール
  shell: fish -lc "fisher add https://gist.github.com/patorash/47e7e179fdd80fe7e9517b93cb2f3d82"
  args:
    creates: ~/.config/fisherman/fish_user_key_bindings

- name: pecoの便利関数のfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/1de94fcb7efeb847501d2fb7900c2deb/raw/7251e11091b388dd527e03c172913e188d1432f6/peco.fish
    dest: ~/.config/fish/conf.d/peco.fish

- name: aliasがまとめられたfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/ca18e28b22f12a55e2539477abcda26d/raw/1ecc260dad5779be94a4304f2980a114ea85e7ac/alias.fish
    dest: ~/.config/fish/conf.d/alias.fish

- name: fishでrbenvを使えるようにする
  blockinfile:
    dest: ~/.config/fish/conf.d/rbenv.fish
    create: true
    block: |
      set -x PATH $HOME/.anyenv/envs/rbenv/bin $PATH
      status --is-interactive; and source (rbenv init -|psub)

- name: .bash_profileの最後でfishを起動させる
  lineinfile:
    dest: ~/.bash_profile
    line: exec fish
