---
- name: homebrewのアップデート
  homebrew:
    update_homebrew=yes

- name: fishのインストール
  homebrew:
    name: fish
    state: latest

- name: fishを選択可能なshellとして追加
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/fish
  become: yes

- name: 既存のshellを確認する
  shell: echo $SHELL
  register: current_shell
  changed_when: false

- name: fishをデフォルトのshellにする
  shell: chsh -s /usr/local/bin/fish
  become: yes
  when: current_shell.stdout != '/usr/local/bin/fish'

- name: oh-my-fishをclone
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish
    dest: ~/oh-my-fish

- name: oh-my-fishをlocalからインストールする
  shell: bin/install --offline --noninteractive
  args:
    chdir: ~/oh-my-fish
    creates: ~/.config/omf

- stat: path=~/.anyenv
  register: anyenv

- name: anyenvの設定を行うfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/b5a1033c08d2c4df103457866b2dcaa2/raw/9a6c7e2111d95db0fdb07d43a41fa2eea5352b5f/anyenv.fish
    dest: ~/.config/fish/conf.d/anyenv.fish
  when: anyenv.stat.exists

- name: pecoの便利関数のfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/1de94fcb7efeb847501d2fb7900c2deb/raw/7251e11091b388dd527e03c172913e188d1432f6/peco.fish
    dest: ~/.config/fish/conf.d/peco.fish

- name: aliasがまとめられたfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/ca18e28b22f12a55e2539477abcda26d/raw/1ecc260dad5779be94a4304f2980a114ea85e7ac/alias.fish
    dest: ~/.config/fish/conf.d/alias.fish

- name: functionsディレクトリを作る
  file:
    path: ~/.config/fish/functions
    state: directory

- name: カスタムキーバインディングのfishファイルをコピーする
  get_url:
    url: https://gist.githubusercontent.com/patorash/47e7e179fdd80fe7e9517b93cb2f3d82/raw/8f74b8614eb0ddc3f3f3ce0c1964117cdbb08fdf/fish_user_key_bindings.fish
    dest: ~/.config/fish/functions/fish_user_key_bindings.fish
    force: true