---
- name: anyenvをcloneする
  git:
    repo: 'https://github.com/riywo/anyenv.git'
    dest: ~/.anyenv

- name: anyenvへのPATHを通す
  lineinfile:
    dest: ~/.bash_profile
    line: "{{ item }}"
  with_items:
    - export PATH="$HOME/.anyenv/bin:$PATH"
    - eval "$(anyenv init -)"

- name: rbenvのインストール
  shell: /bin/bash -lc "anyenv install rbenv"
  args:
    creates: ~/.anyenv/envs/rbenv/bin/rbenv

- name: ndenvのインストール
  shell: /bin/bash -lc "anyenv install ndenv"
  args:
    creates: ~/.anyenv/envs/ndenv/bin/ndenv

- name: Rubyのインストール
  shell: /bin/bash -lc "rbenv install {{ version }} && rbenv rehash"
  args:
    creates: ~/.anyenv/envs/rbenv/versions/{{ version }}
  with_items: "{{ ruby_versions }}"
  loop_control:
    loop_var: version

- name: Nodeのインストール
  shell: /bin/bash -lc "ndenv install {{ version }} && ndenv rehash"
  args:
    creates: ~/.anyenv/envs/ndenv/versions/{{ version }}
  with_items: "{{ node_versions }}"
  loop_control:
    loop_var: version
