---
- name: caskパッケージのインストール
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('installed')}}"
    greedy: true
  with_items:
    - { name: docker }
    - { name: firefox-esr }
    - { name: iterm2 }
    - { name: java }
    - { name: kitematic }
    - { name: rubymine }
    - { name: vagrant }
    - { name: virtualbox}
    - { name: visual-studio-code }
  become: yes
  # failed_when: False
